/*----------------------------------------------------------------------------------------*/
/*
 * File:    main.c
 * Purpose: Entry point that initializes the board, runs startup UI and
 *          sensor calibration, and drives the IMU-controlled 3D object demo.
 * Author:  Jack McBrearty
 *
 * Functions contained in this file:
 * - main: Initializes hardware, runs calibration, and executes the main loop.
 * - SystemClock_Config: Configures the STM32 clock tree.
 * - MX_I2C1_Init: Initializes the I2C peripheral.
 * - MX_GPIO_Init: Initializes GPIO used by the board.
 * - MX_FMC_Init: Initializes the external memory controller.
 * - I2C_Bus_Reset: Recovers the sensor bus by manually toggling the I2C lines.
 * - Error_Handler: Traps the firmware after a fatal startup error.
 * - NormalizeQuat: Normalizes a quaternion in place.
 * - IntegrateQuat: Integrates angular velocity into the object's orientation quaternion.
 * - ComputeSpinCommands: Maps physical tilt into object spin commands.
 * - IsStableForReset: Checks if the box has been still long enough to count as stable.
 * - ResetObjectOrientation: Restores the rendered object to default pose.
 * - QuaternionToEulerDegrees: Converts EKF orientation into roll, pitch, and yaw angles.
 * - FormatAngleLine: Formats one overlay angle line without float printf support.
 * - DrawPoseOverlay: Draws the roll, pitch, and yaw overlay in the top-right corner.
 *
 * Notes:
 * - Portions of this codebase were generated and/or optimized using OpenAI's Codex and
 *   Google's Gemini models. I wanted to tinker with how well these two models worked.
 *   I found Codex to be more accurate and followed instructions better. Gemini would tend
 *   to give up easily if instructions were too vague or results did not produce desired
 *   effects. I had to be careful that it would not try to overwrite large chunks. For
 *   example, while trying to fine tune the Kalman filter parameters, Gemini kept trying
 *   to change the code to a complimentary filter.
 * - Overall I found the AI to be an extremely useful tool. I was worried that embedded
 *   development would be difficult but, I was proven wrong. Codex in particular was great
 *   at identifying the limitations of my specific STM32 chip.
 * - I personally verified any additions/changes made by the AI tools.
 */
/*----------------------------------------------------------------------------------------*/


/*----------------------------------------------------------------------------------------*/
// INCLUDES
/*----------------------------------------------------------------------------------------*/
#include "main.h"
#include "engine3d.h"
#include "sensor_helper.h"
#include "kalman_filter.h"
#include <math.h>


/*----------------------------------------------------------------------------------------*/
// GLOBAL VARIABLES
/*----------------------------------------------------------------------------------------*/
// Global HAL handles generated by STM32CubeMX and shared with other modules.
I2C_HandleTypeDef hi2c1;
SRAM_HandleTypeDef hsram1;

// Latest calibrated sensor samples in engineering units.
static float acceleration_mg[3];
static float angular_rate_mdps[3];
static float mag_val[3];

// Reference vectors captured during the startup calibration step.
static float accel_reference_mg[3];
static float mag_reference[3];

// Application state for the orientation filter and rendered object.
EKF_TypeDef ekf;
static float object_q[4] = {1.0f, 0.0f, 0.0f, 0.0f};


/*----------------------------------------------------------------------------------------*/
// CONSTANTS
/*----------------------------------------------------------------------------------------*/
#define TILT_SPIN_GAIN_X      4.5f   // Scale factor that turns X-axis tilt into object spin speed.
#define TILT_SPIN_GAIN_Y      4.5f   // Scale factor that turns Y-axis tilt into object spin speed.
#define TWIST_SPIN_GAIN       1.2f   // Scale factor that turns Z-axis twist into yaw spin speed.
#define TILT_DEADZONE_G       0.08f  // Min tilt magnitude in g before tilt starts rotating the object.
#define TWIST_DEADZONE_RAD_S  0.12f  // Min twist rate in rad/s before twist starts rotating the object.
#define LEVEL_STOP_G          0.04f  // Tilt threshold below which the box is treated as level for stopping motion.
#define LEVEL_STOP_RAD_S      0.08f  // Twist-rate threshold below which the box is treated as not twisting.
#define STILL_RESET_G         0.05f  // Max tilt magnitude allowed while counting toward auto-reset.
#define STILL_RESET_RAD_S     0.09f  // Max rotation magnitude allowed while counting toward auto-reset.
#define STILL_RESET_TIME_S    10.0f  // Time in seconds the box must remain still before the orientation resets.
#define CAMERA_BASE_HEIGHT_IN 3.8f   // Camera height above the object in inches.


/*----------------------------------------------------------------------------------------*/
// FUNCTION DECLARATIONS
/*----------------------------------------------------------------------------------------*/
static void NormalizeQuat(float q[4]);
static void IntegrateQuat(float q[4], float wx, float wy, float wz, float dt);
static void QuaternionToEulerDegrees(float q0, float q1, float q2, float q3, float *roll_deg, float *pitch_deg, float *yaw_deg);
static void FormatAngleLine(char label, float degrees, char out[8]);
static void DrawPoseOverlay(float roll_deg, float pitch_deg, float yaw_deg);
static void ComputeSpinCommands(const float gravity_body[3], float gz, float *spin_x, float *spin_y, float *spin_z);
static uint8_t IsStableForReset(const float gravity_body[3], float motion_mag);
static void ResetObjectOrientation(void);
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_FMC_Init(void);
static void I2C_Bus_Reset(void);


/*----------------------------------------------------------------------------------------*/
/* Function: main
 * Purpose:  Application entry point. Startup performs hardware initialization,
 *           user-visible calibration screens, and EKF setup. The main loop then reads
 *           sensors, updates the orientation estimate, maps tilt into object motion, and
 *           redraws the scene.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
int main(void)
{
  // Hardware Setup
  HAL_Init();           // Initialize HAL Layer
  SystemClock_Config(); // Initialize clock
  MX_GPIO_Init();       // Enable GPIO pins
  MX_FMC_Init();        // Initialize LCD pins
  I2C_Bus_Reset();      // Reset I2C bus
  MX_I2C1_Init();       // Initialize I2C pins

  // Application Setup
  Engine3D_Init(); // Initialize 3D renderer for UI and object
  Sensors_Init();  // Verify sensors are connected and configure them

  // Startup and Calibration
  Sensors_ShowStartupCountdown();  // Draw startup UI
  Sensors_Calibrate();             // Startup sensors, calculate sensor bias, and draw Calibration UI
  Sensors_ShowInstructionScreen(); // Draw Instruction UI

  // Extended Kalman Filter (EKF) Setup

  // Get the calibrated gravity and magnetometer reference vectors for the EKF.
  Sensors_GetReferenceFrame(accel_reference_mg, mag_reference);

  EKF_Init(&ekf); // Initialize EKF state

  // Load the startup reference frame so the EKF knows what "level" should look like.
  EKF_SetReference(&ekf,
                   // Accelerometer reference X, mg to g.
                   accel_reference_mg[0] / 1000.0f,
                   // Accelerometer reference Y, mg to g.
                   accel_reference_mg[1] / 1000.0f,
                   // Accelerometer reference Z, mg to g.
                   accel_reference_mg[2] / 1000.0f,
                   // Magnetometer reference X.
                   mag_reference[0],
                   // Magnetometer reference Y.
                   mag_reference[1],
                   // Magnetometer reference Z.
                   mag_reference[2]);

  uint32_t last_tick = HAL_GetTick(); // Current tick count, used for delta time
  float still_time_s = 0.0f;          // Time box has remained still, used for auto-reset

  // Main Infinite Loop
  while (1)
  {
    // Read the latest sensor samples.
    Sensors_Read(acceleration_mg, angular_rate_mdps, mag_val);

    // Convert gyroscope units from milli-degrees per sec (mdps) into radians per second for the EKF.
    float gx = (angular_rate_mdps[0] / 1000.0f) * (M_PI / 180.0f); // X axis
    float gy = (angular_rate_mdps[1] / 1000.0f) * (M_PI / 180.0f); // Y axis
    float gz = (angular_rate_mdps[2] / 1000.0f) * (M_PI / 180.0f); // Z axis

    // Calculate delta time from elapsed tick count
    uint32_t tick = HAL_GetTick(); // Current tick count,
    float dt = (tick > last_tick) ? ((float)(tick - last_tick) / 1000.0f) : 0.01f; // delta time
    last_tick = tick;              // Update last tick to current

    if (dt < 0.005f) dt = 0.005f; // Clamp delta time if too small
    if (dt > 0.03f) dt = 0.03f;   // Clamp delta time if too large

    EKF_Predict(&ekf, gx, gy, gz, dt); // Predict next state from gyro values

    // Convert accelerometer units from mg into g for the EKF update step.
    float ax = acceleration_mg[0] / 1000.0f; // X axis
    float ay = acceleration_mg[1] / 1000.0f; // Y axis
    float az = acceleration_mg[2] / 1000.0f; // Z axis

    if (mag_available) {
        // Magnetometer connected, update EKF with all accel and mag values */
        EKF_Update(&ekf, ax, ay, az, mag_val[0], mag_val[1], mag_val[2]);
    } else {
        // Magnetometer disconnected, update EKF with only accel values
        EKF_Update(&ekf, ax, ay, az, 0, 0, 0);
    }

    // Pull the current quaternion estimate out of the EKF state vector.
    float q0 = ekf.x_hat_data[0];
    float q1 = ekf.x_hat_data[1];
    float q2 = ekf.x_hat_data[2];
    float q3 = ekf.x_hat_data[3];

    // Gravity estimate in body coordinates, derived from the quaternion.
    float gravity_body[3];

    // Angular velocity commands that will be applied to the rendered object.
    float spin_x;
    float spin_y;
    float spin_z;

    // Euler-angle versions of the current EKF orientation for the text overlay.
    float roll_deg;
    float pitch_deg;
    float yaw_deg;

    // Combined angular-motion magnitude used by the stillness detector.
    float motion_mag;

    // If the EKF state becomes invalid, reset it and skip this frame to recover cleanly.
    if (isnan(q0)) { EKF_Init(&ekf); continue; }

    // Estimate gravity in body coordinates from the EKF orientation.
    gravity_body[0] = 2.0f * (q1*q3 - q0*q2);        // X axis
    gravity_body[1] = 2.0f * (q2*q3 + q0*q1);        // Y axis
    gravity_body[2] = q0*q0 - q1*q1 - q2*q2 + q3*q3; // Z axis

    // Turn physical tilt into angular velocity commands for the object.
    ComputeSpinCommands(gravity_body, gz, &spin_x, &spin_y, &spin_z);

    // Integrate those spin commands so the rendered object continues moving smoothly.
    IntegrateQuat(object_q, spin_x, spin_y, spin_z, dt);

    // Auto-reset after a long still hold so the demo can recover itself.
    // Treat the total gyro magnitude as a simple measure of how much the box is rotating.
    motion_mag = sqrtf(gx * gx + gy * gy + gz * gz);

    // Check whether the box is still
    if (IsStableForReset(gravity_body, motion_mag)) {
        still_time_s += dt; // Box is still, increment time

        if (still_time_s >= STILL_RESET_TIME_S) {
            ResetObjectOrientation(); // Box has been idle long enough, reset orientation
            still_time_s = 0.0f;      // Reset timer
        }
    } else {
        still_time_s = 0.0f; // Box is moving, reset timer
    }

    // Compute the display angles shown in the row/pitch/yaw overlay.
    QuaternionToEulerDegrees(q0, q1, q2, q3, &roll_deg, &pitch_deg, &yaw_deg);

    // Render the object from a fixed camera position.
    Engine3D_SetCameraPose(0.0f, 0.0f, CAMERA_BASE_HEIGHT_IN);

    // Pass the updated object quaternion to the renderer.
    Engine3D_SetObjectRotation(object_q[0], object_q[1], object_q[2], object_q[3]);

    // Project the 3D wireframe into 2D line segments for this frame.
    Engine3D_PrepareFrame(); //

    // Draw the scene
    GPU_Render(Engine3D_DrawScene);

    // Draw row/pitch/yaw overlay
    DrawPoseOverlay(roll_deg, pitch_deg, yaw_deg);
  }
}

/*----------------------------------------------------------------------------------------*/
/* Function: SystemClock_Config
 * Purpose:  Configure the STM32 system clocks. This is the standard CubeMX-generated clock
 *           tree setup for the board.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI|RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 15;
  RCC_OscInitStruct.PLL.PLLN = 144;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 5;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) Error_Handler();
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK) Error_Handler();
}

/*----------------------------------------------------------------------------------------*/
/* Function: MX_I2C1_Init
 * Purpose:  Initialize the I2C peripheral used by the IMU devices.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
void MX_I2C1_Init(void)
{
  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK) Error_Handler();
}

/*----------------------------------------------------------------------------------------*/
/* Function: MX_GPIO_Init
 * Purpose:  Enable and initialize the GPIO blocks used by the project. Most of the
 *           detailed pin muxing is board-specific and generated by STM32Cube.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
void MX_GPIO_Init(void)
{
  __HAL_RCC_GPIOE_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(GPIOD, GPIO_PIN_3, GPIO_PIN_RESET);
}

/*----------------------------------------------------------------------------------------*/
/* Function: MX_FMC_Init
 * Purpose:  Initialize the external memory controller for the LCD interface.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void MX_FMC_Init(void)
{
  FMC_NORSRAM_TimingTypeDef Timing = {0};
  hsram1.Instance = FMC_NORSRAM_DEVICE;
  hsram1.Extended = FMC_NORSRAM_EXTENDED_DEVICE;
  hsram1.Init.NSBank = FMC_NORSRAM_BANK1;
  hsram1.Init.DataAddressMux = FMC_DATA_ADDRESS_MUX_DISABLE;
  hsram1.Init.MemoryType = FMC_MEMORY_TYPE_SRAM;
  hsram1.Init.MemoryDataWidth = FMC_NORSRAM_MEM_BUS_WIDTH_16;
  hsram1.Init.BurstAccessMode = FMC_BURST_ACCESS_MODE_DISABLE;
  hsram1.Init.WaitSignalPolarity = FMC_WAIT_SIGNAL_POLARITY_LOW;
  hsram1.Init.WrapMode = FMC_WRAP_MODE_DISABLE;
  hsram1.Init.WaitSignalActive = FMC_WAIT_TIMING_BEFORE_WS;
  hsram1.Init.WriteOperation = FMC_WRITE_OPERATION_ENABLE;
  hsram1.Init.WaitSignal = FMC_WAIT_SIGNAL_DISABLE;
  hsram1.Init.ExtendedMode = FMC_EXTENDED_MODE_DISABLE;
  hsram1.Init.AsynchronousWait = FMC_ASYNCHRONOUS_WAIT_DISABLE;
  hsram1.Init.WriteBurst = FMC_WRITE_BURST_DISABLE;
  hsram1.Init.ContinuousClock = FMC_CONTINUOUS_CLOCK_SYNC_ONLY;
  hsram1.Init.PageSize = FMC_PAGE_SIZE_NONE;
  Timing.AddressSetupTime = 5;
  Timing.AddressHoldTime = 0;
  Timing.DataSetupTime = 9;
  Timing.BusTurnAroundDuration = 0;
  Timing.CLKDivision = 16;
  Timing.DataLatency = 17;
  Timing.AccessMode = FMC_ACCESS_MODE_A;
  if (HAL_SRAM_Init(&hsram1, &Timing, NULL) != HAL_OK) Error_Handler();
}

/*----------------------------------------------------------------------------------------*/
/* Function: I2C_Bus_Reset
 * Purpose: Manually toggle the I2C bus lines to recover from a stuck peripheral. This is
 *          useful on power-up when one of the sensors holds SDA/SCL in an unexpected state.
 * Returns: none
 */
/*----------------------------------------------------------------------------------------*/
void I2C_Bus_Reset(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  __HAL_RCC_GPIOB_CLK_ENABLE();
  GPIO_InitStruct.Pin = GPIO_PIN_6 | GPIO_PIN_7;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_OD;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET);
  HAL_Delay(5);
  for(int i = 0; i < 9; i++)
  {
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET);
    HAL_Delay(5);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET);
    HAL_Delay(5);
  }
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET);
  HAL_Delay(5);
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET);
  HAL_Delay(5);
  HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET);
  HAL_Delay(5);
  HAL_GPIO_DeInit(GPIOB, GPIO_PIN_6 | GPIO_PIN_7);
}

/*----------------------------------------------------------------------------------------*/
/* Function: Error_Handler
 * Purpose:  Trap the firmware in an infinite loop after a fatal initialization error.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
void Error_Handler(void)
{
  __disable_irq();
  while (1) {}
}

/*----------------------------------------------------------------------------------------*/
/* Function: NormalizeQuat
 * Purpose:  Normalize the quaternion after updates so the rotation state remains a valid
 *           unit quaternion and does not drift from accumulated numerical error.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void NormalizeQuat(float q[4])
{
  // Compute the quaternion magnitude so it can be scaled back to unit length.
  float norm = sqrtf(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]);

  // If the norm is large enough to be safe, divide each component by that norm.
  if (norm > 1e-6f) {
    // Normalize the scalar, X, Y, and Z components.
    q[0] /= norm;
    q[1] /= norm;
    q[2] /= norm;
    q[3] /= norm;
  } else {
    // If the quaternion collapses numerically, fall back to the identity rotation.
    q[0] = 1.0f;
    q[1] = 0.0f;
    q[2] = 0.0f;
    q[3] = 0.0f;
  }
}

/*----------------------------------------------------------------------------------------*/
/* Function: IntegrateQuat
 * Purpose:  Apply angular velocity over the current time step to update the object's
 *           orientation quaternion, which controls how the hammer is rendered.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void IntegrateQuat(float q[4], float wx, float wy, float wz, float dt)
{
  float q_dot[4];  // Temporary quaternion derivative used for one integration step.

  q_dot[0] = 0.5f * (-q[1] * wx - q[2] * wy - q[3] * wz); // Change in scalar component.
  q_dot[1] = 0.5f * ( q[0] * wx + q[2] * wz - q[3] * wy); // Change in X vector component.
  q_dot[2] = 0.5f * ( q[0] * wy - q[1] * wz + q[3] * wx); // Change in Y vector component.
  q_dot[3] = 0.5f * ( q[0] * wz + q[1] * wy - q[2] * wx); // Change in Z vector component.

  q[0] += q_dot[0] * dt; // Advance the scalar term by the current frame time.
  q[1] += q_dot[1] * dt; // Advance the X component by the current frame time.
  q[2] += q_dot[2] * dt; // Advance the Y component by the current frame time.
  q[3] += q_dot[3] * dt; // Advance the Z component by the current frame time.
  NormalizeQuat(q);      // Re-normalize so the quaternion stays a valid unit rotation.
}

/*----------------------------------------------------------------------------------------*/
/* Function: ComputeSpinCommands
 * Purpose:  Convert the measured gravity direction and twist rate into x, y, and z spin
 *           commands, including dead zones so small sensor noise does not rotate the object.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void ComputeSpinCommands(const float gravity_body[3], float gz,
                                float *spin_x, float *spin_y, float *spin_z)
{
  // Map X tilt to spin or zero it if under the deadzone.
  *spin_x = fabsf(gravity_body[0]) > TILT_DEADZONE_G ? (gravity_body[0] * TILT_SPIN_GAIN_X) : 0.0f;
  // Map Y tilt to spin and invert direction to match screen motion.
  *spin_y = fabsf(gravity_body[1]) > TILT_DEADZONE_G ? (-gravity_body[1] * TILT_SPIN_GAIN_Y) : 0.0f;
  // Map Z twist rate to yaw spin or ignore tiny twists.
  *spin_z = fabsf(gz) > TWIST_DEADZONE_RAD_S ? (gz * TWIST_SPIN_GAIN) : 0.0f;

  if (fabsf(gravity_body[0]) < LEVEL_STOP_G && fabsf(gravity_body[1]) < LEVEL_STOP_G && fabsf(gz) < LEVEL_STOP_RAD_S) {
    // Force spin to stop when the box is effectively level and not twisting
    *spin_x = 0.0f;
    *spin_y = 0.0f;
    *spin_z = 0.0f;
  }
}

/*----------------------------------------------------------------------------------------*/
/* Function: IsStableForReset
 * Purpose:  Check whether the box is level enough and moving slowly enough to count as
 *           "still", which allows the timed automatic reset to start counting.
 * Returns:  1 if the box is stable enough to count as still, otherwise 0.
 */
/*----------------------------------------------------------------------------------------*/
static uint8_t IsStableForReset(const float gravity_body[3], float motion_mag)
{
  return (fabsf(gravity_body[0]) < STILL_RESET_G) && // Require X tilt to remain within the stillness threshold.
         (fabsf(gravity_body[1]) < STILL_RESET_G) && // Require Y tilt to remain within the stillness threshold.
         (motion_mag < STILL_RESET_RAD_S);           // Require overall angular motion to remain very small.
}

/*----------------------------------------------------------------------------------------*/
/* Function: ResetObjectOrientation
 * Purpose:  Reset the rendered object's quaternion to the identity rotation so the demo
 *           returns to its default orientation after a long still hold.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void ResetObjectOrientation(void)
{
  object_q[0] = 1.0f; // Identity quaternion scalar term.
  object_q[1] = 0.0f; // Identity quaternion X component.
  object_q[2] = 0.0f; // Identity quaternion Y component.
  object_q[3] = 0.0f; // Identity quaternion Z component.
}

/*----------------------------------------------------------------------------------------*/
/* Function: QuaternionToEulerDegrees
 * Purpose:  Convert the EKF quaternion into roll, pitch, and yaw angles in degrees for
 *           the debug overlay shown in the upper-right corner of the screen.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void QuaternionToEulerDegrees(float q0, float q1, float q2, float q3,
                                     float *roll_deg, float *pitch_deg, float *yaw_deg)
{
  float sinr_cosp = 2.0f * (q0 * q1 + q2 * q3);        // Sine/cosine helper term for roll.
  float cosr_cosp = 1.0f - 2.0f * (q1 * q1 + q2 * q2); // Sine/cosine helper term for roll.
  float sinp = 2.0f * (q0 * q2 - q3 * q1);             // Sine helper term for pitch.
  float siny_cosp = 2.0f * (q0 * q3 + q1 * q2);        // Sine/cosine helper term for yaw.
  float cosy_cosp = 1.0f - 2.0f * (q2 * q2 + q3 * q3); // Sine/cosine helper term for yaw.
  float pitch_rad;                                     // Temporary pitch angle in radians.

  *roll_deg = atan2f(sinr_cosp, cosr_cosp) * (180.0f / (float)M_PI); // Convert roll to degrees.

  if (fabsf(sinp) >= 1.0f) {
    pitch_rad = copysignf((float)M_PI / 2.0f, sinp); // Clamp pitch at +/-90 degrees near gimbal lock.
  } else {
    pitch_rad = asinf(sinp); // Normal pitch conversion when inside valid asin range.
  }

  *pitch_deg = pitch_rad * (180.0f / (float)M_PI); // Convert pitch from radians to degrees.
  *yaw_deg = atan2f(siny_cosp, cosy_cosp) * (180.0f / (float)M_PI); // Convert yaw to degrees.
}

/*----------------------------------------------------------------------------------------*/
/* Function: FormatAngleLine
 * Purpose:  Build a short fixed-width text string for one angle line without relying on
 *           floating-point printf support, which is often disabled in embedded builds.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void FormatAngleLine(char label, float degrees, char out[8])
{
  int value = (int)(degrees >= 0.0f ? degrees + 0.5f : degrees - 0.5f); // Round the float angle to the nearest integer.
  int abs_value; // Store the absolute value for digit extraction.

  if (value > 999) value = 999;           // Clamp very large positive values to the display width.
  if (value < -999) value = -999;         // Clamp very large negative values to the display width.
  abs_value = value < 0 ? -value : value; // Remove the sign temporarily so the digits can be split out.

  out[0] = label;                                  // First character is the axis label: R, P, or Y.
  out[1] = ' ';                                    // Insert a space after the label for readability.
  out[2] = (value < 0) ? '-' : ' ';                // Show a minus sign only for negative values.
  out[3] = (char)('0' + ((abs_value / 100) % 10)); // Hundreds digit.
  out[4] = (char)('0' + ((abs_value / 10) % 10));  // Tens digit.
  out[5] = (char)('0' + (abs_value % 10));         // Ones digit
  out[6] = '\0';                                   // Null terminator so GPU_DrawText sees a valid C string.
}

/*----------------------------------------------------------------------------------------*/
/* Function: DrawPoseOverlay
 * Purpose:  Draw the roll, pitch, and yaw values in the top-right corner after the main
 *           scene is rendered so the diagnostic text stays visible on top of the object.
 * Returns:  none
 */
/*----------------------------------------------------------------------------------------*/
static void DrawPoseOverlay(float roll_deg, float pitch_deg, float yaw_deg)
{
  char line[8];  // Temporary string buffer used for each overlay line.

  GPU_FillRect(368, 8, 104, 32, COLOR_BLACK);  // Clear the old overlay.
  FormatAngleLine('R', roll_deg, line);                 // Build the roll text line.
  GPU_DrawText(374, 10, line, COLOR_WHITE, 1); // Draw roll near the top of the overlay box.
  FormatAngleLine('P', pitch_deg, line);                // Build the pitch text line.
  GPU_DrawText(374, 20, line, COLOR_WHITE, 1); // Draw pitch on the middle line.
  FormatAngleLine('Y', yaw_deg, line);                  // Build the yaw text line.
  GPU_DrawText(374, 30, line, COLOR_WHITE, 1); // Draw yaw on the bottom line.
}
